/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import ScaleAnimScript from "./module/common/component/ScaleAnimScript"
import DaySignItem from "./module/daySign/view/DaySignItem"
import GuideSpeakView from "./module/guide/view/GuideSpeakView"
import HallScene from "./module/hall/view/HallScene"
import CurrencyView from "./module/hall/view/CurrencyView"
import HeadItem from "./module/hall/view/item/HeadItem"
import SystemBtn from "./module/hall/view/item/SystemBtn"
import LoginScene from "./module/login/view/LoginScene"
import RollNameItem from "./module/luckPrize/view/item/RollNameItem"
import RankItem from "./module/rank/view/RankItem"
import ShopItem from "./module/shop/view/ShopItem"
import TaskItem from "./module/task/view/TaskItem"
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=750;
    static height:number=1334;
    static scaleMode:string="fixedwidth";
    static screenMode:string="none";
    static alignV:string="middle";
    static alignH:string="center";
    static startScene:any="moduleView/login/LoginScene.scene";
    static sceneRoot:string="";
    static debug:boolean=false;
    static stat:boolean=true;
    static physicsDebug:boolean=false;
    static exportSceneToJson:boolean=true;
    constructor(){}
    static init(){
        var reg: Function = Laya.ClassUtils.regClass;
        reg("module/common/component/ScaleAnimScript.ts",ScaleAnimScript);
        reg("module/daySign/view/DaySignItem.ts",DaySignItem);
        reg("module/guide/view/GuideSpeakView.ts",GuideSpeakView);
        reg("module/hall/view/HallScene.ts",HallScene);
        reg("module/hall/view/CurrencyView.ts",CurrencyView);
        reg("module/hall/view/item/HeadItem.ts",HeadItem);
        reg("module/hall/view/item/SystemBtn.ts",SystemBtn);
        reg("module/login/view/LoginScene.ts",LoginScene);
        reg("module/luckPrize/view/item/RollNameItem.ts",RollNameItem);
        reg("module/rank/view/RankItem.ts",RankItem);
        reg("module/shop/view/ShopItem.ts",ShopItem);
        reg("module/task/view/TaskItem.ts",TaskItem);
    }
}
GameConfig.init();